version: 'v1.0.0'
services:
  web:
    build: .
    ports:
      - 5000:5000
    environment:
      # - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
    volumes:
      - ./code:/code